version: 0.2

phases:
  pre_build:
    commands:
      - go mod download

  build:
    commands:
      - go build -o signalrsrv-linux

artifacts:
  files:
    - signalrsrv-linux
    - signalRconfig.json
    - public/*