version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION 
      - echo "Rocky@19721007" | docker login --username "iacfdev@gmail.com" --password-stdin $ECR_REGISTRY_URL


  build:
    commands:
      - echo "Building your Go application"
      - docker build -t iac-signalrsrv .
      - docker tag iac-signalrsrv:latest $ECR_REGISTRY_URL/iac-signalrsrv:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push $ECR_REGISTRY_URL/iac-signalrsrv:latest