version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo "Installing dependencies or other pre-build steps"

  build:
    commands:
      - echo "Building your Go application"

  post_build:
    commands:
      - echo "Post-build steps, such as deployment"